name: Cron Test Every Minute

on:
  schedule:
    - cron: '*/1 * * * *' # ทุก 1 นาที
  workflow_dispatch: # เผื่ออยากรันเองด้วยมือ

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "⏰ Running at $(date)"
